### ISSUE TITLE
Can't install module with NPM

### ISSUE THREAD

**Issue by TTATPuOT** [Hackzzila/node-ffmpeg-binaries#15]
Hello!
I try to install package by NPM with command:
```
npm install
```
and had error:
```
3304` verbose stack Error: ffmpeg-binaries@4.0.0 install: `node install`
3304 verbose stack Exit status 1
3304 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
3304 verbose stack     at emitTwo (events.js:126:13)
3304 verbose stack     at EventEmitter.emit (events.js:214:7)
3304 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3304 verbose stack     at emitTwo (events.js:126:13)
3304 verbose stack     at ChildProcess.emit (events.js:214:7)
3304 verbose stack     at maybeClose (internal/child_process.js:925:16)
3304 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
3305 verbose pkgid ffmpeg-binaries@4.0.0
3306 verbose cwd /home/n/neverov12/patriotovsky.ru/public_html/nodejs/discrod_buhgalter
3307 verbose Linux 4.9.80-0-beget-acl
3308 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ffmpeg-binaries" "--save"
3309 verbose node v8.9.1
3310 verbose npm  v5.5.1
3311 error code ELIFECYCLE
3312 error errno 1
3313 error ffmpeg-binaries@4.0.0 install: `node install`
3313 error Exit status 1
3314 error Failed at the ffmpeg-binaries@4.0.0 install script.
3314 error This is probably not a problem with npm. There is likely additional logging output above.
3315 verbose exit [ 1, true ]
[2018-10-16t00_04_50_923z-debug (1).log](https://github.com/Hackzzila/node-ffmpeg-binaries/files/2494154/2018-10-16t00_04_50_923z-debug.1.log)

```
Full log file with error attached.
package.json:
```
{
  "name": "discord_bot",
  "version": "0.0.1",
  "dependencies": {
    "bufferutil": "^4.0.0",
    "cheerio": "^1.0.0-rc.2",
    "cors": "^2.8.4",
    "discord.js": "^11.4.2",
    "express": "^4.16.3",
    "ffmpeg-binaries": "^4.0.0",
    "iconv-lite": "^0.4.24",
    "mysql": "github:mysqljs/mysql",
    "opusscript": "0.0.6",
    "request": "^2.88.0",
    "winston": "^3.0.0",
    "yandex-speech": "0.0.14"
  }
}
```
All works fine on my Windows PC, but on hosting server it's not working.
Server: Ubuntu Server Edition 12.04

**Comment by TTATPuOT** [comment]
Resolve. For install this module need **glibc** libraray version at least 2.17. I had a 2.15 on server and it's broke install.
